### ISSUE TITLE
Old TK let's you teleport people to you when throwing

### ISSUE THREAD

**Issue by PrimeNumb** [goonstation/goonstation#558] opened 2020-05-03 17:12 UTC
[BUG]

**Describe the bug**
Title.

**To Reproduce**
1. Knock someone down
2. Activate old TK (Empower, etc)
3. Grab the knocked down person
4. Throw the person and see error

**Expected behavior**
Throwing them, but not teleporting them to you first.

**Comment by UrsulaMejor** [comment] 2020-05-03 17:16
Confirmed replicateable.

**Comment by zjdtmkhzt** [comment] 2020-05-03 17:22
If you really think about it, it makes just as much sense as being able to grab items through walls and stuff. I guess the assumption is that you just kind of "float it over"? The same assumption could be made for grabbing people.
I think if this is fixed, it should be for balance reason, because from a logic perspective it kind of makes sense to be able to teleport things to you. Also, seeing as the only ways to get old tk nowadays are magical, I guess teleporting people and things would fit in too?

So I am not sure if I would classify this as a bug, grabbing people pulls them to you, so it makes just as much sense to me as being able to teleport items to yourself.

**Comment by PrimeNumb** [comment] 2020-05-03 17:24
Idk, I thought it was intended but Emily said it wasn't so

**Comment by UrsulaMejor** [comment] 2020-05-03 17:42
> So I am not sure if I would classify this as a bug, grabbing people pulls them to you, so it makes just as much sense to me as being able to teleport items to yourself.

The fact that the grab auto cancels if you do anything except this very specific chain of events signals to me that this is an oversight.

**Comment by zjdtmkhzt** [comment] 2020-05-03 18:35
Isn't that just a natural result of grabs breaking when getting to far away from a person? I wouldn't take that as intent that you should not be able to grab people with old tk. (Not that I disapprove of changing it, I don't really have an opinion on that matter.)

**Comment by Gerhazo** [comment] 2020-05-03 19:40
I believe the reason it's "old tk" is because it was very simple in how it worked and by extension broken in terms of what you could do, hence the reason it was dumped and replaced with something that was actually sensible from gameplay and expectations standpoint.

And if it's to remain as a throwback/upgraded version as it does now, things like these probably should be fixed, both in terms of balance and not making sense, potentially extending to other parts of it, though that's out of scope of what this issue's discussing.

**Comment by Kyle2143** [comment] 2020-05-03 20:48
Yeah, this is for sure a bug. I noticed it last week but forgot to do anything about it. I think this can be fixed simply by checking if the grabbed target is adjacent to the grabber before throwing the target. I know old tk is kinda crazy, but this is too crazy when its a normal thing in game.

**Comment by flrsh** [comment] 2020-05-21 04:31
Fixed in #762.

**Closed by flrsh** 2020-05-21 04:31 UTC
Labels: bug
