### ISSUE TITLE
iv stands disappear when an iv bag is put on them

### ISSUE THREAD

**Issue by mopcat** [goonstation/goonstation#4444] opened 2021-04-24 03:12 UTC
[BUG]

**Describe the bug**
iv stands disappear when an iv bag is placed on them

**To Reproduce**
1. locate both an iv stand and iv bag
2. place iv bag on iv stand
3. look upon the floating bag
4. horror

**Expected behavior**
the iv stand does not disappear upon having a bag placed upon it

**Screenshots**
![image](https://user-images.githubusercontent.com/65687976/115945341-492b9580-a489-11eb-9a4f-94b5e5a6e4be.png)

**Comment by Tarmunora** [comment] 2021-04-24 03:28
duplicate of #4428

**Comment by Tarmunora** [comment] 2021-04-24 03:28
but this is a better written issue

**Comment by Tarmunora** [comment] 2021-04-24 05:07
fixed

**Closed by Tarmunora** 2021-04-24 05:07 UTC
Labels: bug
