### ISSUE TITLE
Dead hen clucks

### ISSUE THREAD

**Issue by SebastianWaterhouse** [goonstation/goonstation#3795] opened 2021-02-21 19:32 UTC
[BUG]

**Describe the bug**
Dead hen clucks when pet

**To Reproduce**
1. Allow hen to die (possibly only of old age)
2. Pet hen
3. Hen clucks

**Expected behavior**
Hen doesn't cluck

**Screenshots**
![image](https://user-images.githubusercontent.com/5074117/108636169-3674f000-7449-11eb-861a-c8c31b5a8ae7.png)

**Comment by nefarious6th** [comment] 2021-02-22 16:13
Duplicate of #3620 . Someone let these poor chickens rest!

**Comment by BatElite** [comment] 2021-06-13 17:02
Duplicate & fixed according to Emily

**Closed by BatElite** 2021-06-13 17:02 UTC
Labels: bug
