### ISSUE TITLE
Disaster round chat spam

### ISSUE THREAD

**Issue by GB553** [goonstation/goonstation#14004] opened 2023-05-07 13:06 UTC
### Labels

[BUG]

### Description

Some mobs, like the transposed scientist, spam the chat in a way that causes lag and even possible crashing the longer the disaster round goes.

### Steps to reproduce

1.  Start a disaster round
2. Notice the ever increasing lag that becomes unbearable as a ghost
3. Also notice the insane amount of chat spam as a ghost

### Expected Behavior

I expected it not to lag

**Comment by TheTyrant25** [comment] 2023-05-07 13:21
duplicate of #13963

**Closed** 2023-05-07 13:21 UTC
Labels: C-Bug
