### ISSUE TITLE
Full viral immunity doesn't protect against diseases/etc

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#16593] opened 2023-10-21 20:42 UTC
### Labels

[BUG]

### Description

Title

### Steps to reproduce

1. Wear full biosuit and sterile mask
2. Contract airborne, fake GBS

### Expected Behavior

For you to not contract diseases

**Comment by gear-space** [comment] 2023-12-12 14:12
Same root cause and will be fixed as part of the PR associated with #10638 .

**Closed by gear-space** 2023-12-12 14:12 UTC
Labels: C-Bug
