### ISSUE TITLE
middle name field re-populated each fresh connection

### ISSUE THREAD

**Issue by drgg** [goonstation/goonstation#19558] opened 2024-06-17 12:43 UTC
### Labels

[BUG]

### Description

middle name field re-populated each fresh connection

### Steps to reproduce

1. Have a character setup with an empty middle name saved on the server
2. experience a server restart between rounds or simply quit and reconnect to the server
3. there is now a randomly generated name in the middle name field

### Expected Behavior

expected that the empty field would save and persist between connections

### Additional Information & Screenshots

server profile slots and cloud saves DO save the empty middle name slot properly, so a current workaround of loading the profile anew each round/connection (or manually deleting the generated name) is present

**Comment by Glamurio** [comment] 2024-06-18 13:23
Could not reproduce, 80% sure this was fixed by #19508

**Comment by drgg** [comment] 2024-06-18 15:21
just for my own sanity and to make sure im not doing something stupid, here's a video of it being reproduced on my side

https://github.com/goonstation/goonstation/assets/9405689/ca5d3870-3650-458b-9c15-99f6a589b012

what i've tried: updated byond from 1637 to the latest version to make sure it wasnt that, cleared cache and restarted byond in between reconnects too, made a new character profile and overwrote profile slot 1 with a custom middle name (that persisted after rejoining), then submitted an empty field, it still populated by a randomly generated one after saving and reconnecting

**Comment by soleilan** [comment] 2024-06-18 17:22
Can confirm reproducible, your first and main profile on said server has to have no middle name. When you connect to server, the middle name will be populated by a random name, but subsequent manual character loads will function as expected. 

So some code somewhere must be seeing no middle name and adding one, or the loading of a character profile isn't overriding the initial random name for the middle name?

**Comment by pgmzeta** [comment] 2024-11-25 19:37
312f63cf0200fc706deb401c29d887c1df16409b

**Closed by pgmzeta** 2024-11-25 19:37 UTC
Labels: C-Bug, E-Verified
