### ISSUE TITLE
[Critical] Botany mister doesn't fill botany grow trays anymore

### ISSUE THREAD

**Issue by Catsinamansuit** [goonstation/goonstation#16073] opened 2023-09-28 07:23 UTC
### Labels

[BUG]

### Description

Botany mister no longer fills botany trays.

### Steps to reproduce

1. Turn on botany mister
2. Tray contents remain unchanged, mister contents remain at 100%

### Expected Behavior

Mister is supposed to fill the trays.

**Comment by zjdtmkhzt** [comment] 2023-09-28 07:56
caused by 3724ac5267825ed62b657954daadbd734cca1c25 i believe

**Comment by Catsinamansuit** [comment] 2023-09-28 08:18
Did.  They forget to label the botany trays as a open container?  Not really sure.  Thanks for picking this up by the way.  Appreciate it.

**Comment by TobleroneSwordfish** [comment] 2023-09-29 16:29
Fixed by 0e2444f but I'll let zjd and Tyrant argue over the open containerness of plantpots: #16076 #16075

**Closed by TobleroneSwordfish** 2023-09-29 16:29 UTC
Labels: C-Bug, P-Critical, A-Chemistry, A-Hydroponics
