### ISSUE TITLE
Stacking more than 50 sheets

### ISSUE THREAD

**Issue by StanislavN1** [goonstation/goonstation#12590] opened 2023-01-01 08:22 UTC
### Labels

[BUG][MINOR]

### Description

You can stack more that 50 sheets in a stack

### Steps to reproduce

1. Order at least two crates of 200 sheets
2. Pick up one 200 sheet stack
3. Pick up another 200 sheet stack with same hand
4. Result : +150 sheets in that hand, other 50 are in a different stack

### Expected Behavior

Not being able to stack sheets if you have more than 50 of them in that stack

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/68325815/210164831-d03b9163-8fef-4a6f-9c4b-15a8401323df.png)

**Comment by TealSeer** [comment] 2023-10-10 21:20
Duplicate of #16303

**Closed by TealSeer** 2023-10-10 21:20 UTC
Labels: C-Bug, P-Minor
