### ISSUE TITLE
Cyborg eyes do not update their colour when it's changed

### ISSUE THREAD

**Issue by SirSnek** [goonstation/goonstation#4811] opened 2021-05-21 07:37 UTC
[BUG]

**Describe the bug**
When you try to change the eye colour of a cyborg both as a human and cyborg inside the dock it doesn't change

**To Reproduce**
1. Put cyborg in dock
2. Try to change eye colour
3. It does not change

**Expected behavior**
The eyes change like they used to

**Screenshots**

**Additional context**
I was a roundstart light cyborg

**Comment by Gerhazo** [comment] 2021-05-21 08:34
Possibly related to/caused by a runtime in robot.dm line 2568 "bad color", which itself might possibly be related to #3988 or 0caa25c1c1ca3a11a503f0db44f94807c9c2c8cf

example of such call stack, appears to happen consistently on choosing a module
[https://cdn.discordapp.com/attachments/412408851980222465/845217084010790922/unknown.png](url)

From some personal testing: changing eye color works before choosing a module. After I choose a medical module, the runtime above happens and any subsequent attempts at changing eye color also cause the runtime.

**Comment by FlameArrow57** [comment] 2022-09-17 05:13
Seems to have been fixed with new cyborg docking station

**Closed by FlameArrow57** 2022-09-17 05:13 UTC
Labels: C-Bug, C-Runtime
