### ISSUE TITLE
Paper with form fields written on it shows up as blank

### ISSUE THREAD

**Issue by keiyakins** [goonstation/goonstation#587] opened 2020-05-05 20:42 UTC
[BUG]

**Describe the bug**
If you put a form field on a piece of paper (using underscores) the entire text of the paper shows up as blank. 

**To Reproduce**
1. Get a pen and a piece of paper
2. Write something on the paper that includes a form field
3. Examine the paper

**Expected behavior**
I'd expect to see the form... or at least the textual parts!

**Screenshots**
![image](https://user-images.githubusercontent.com/161285/81114049-d9727280-8ee6-11ea-8197-5a1adc4786bc.png)
![image](https://user-images.githubusercontent.com/161285/81114072-e1caad80-8ee6-11ea-9251-e05eb74fe418.png)

**Additional context**
I did have a couple other players look at my test forms, so it's not just me.

**Comment by triacontakai** [comment] 2020-05-05 22:09
Possibly caused by #498 given that was merged 5 days ago.

**Closed** 2020-05-06 06:38 UTC
Labels: bug
