### ISSUE TITLE
context menu pickup organs clicks the person instead

### ISSUE THREAD

**Issue by kotomato** [goonstation/goonstation#8592] opened 2022-05-14 20:53 UTC
### Labels

[BUG]

### Description

if you attempt to pick up an organ through the right click context menu but are adjacent to someone bearing the same name as the organ's owner it will click them instead

### Steps to reproduce

1. acquire assistant
2. surgery out their brain or other organs (not skull, this changes their identity)
3. attempt to pick up the organ via the right click context menu
4. watch as character instead interacts with the assistant for some reason

### Expected Behavior

interact with the organ and not the person i took it from

### Additional Information & Screenshots

the name has to be the same exactly. if they're unknown it will pick up the organ just fine, same if they have the wrong ID on.
for a maybe better description of how the bug works: 

say you have an assistant named Kade Hunter. you surgery out something of them, which will come out as Kade Hunter's [organ]. when you are adjacent to both Kade Hunter and Kade Hunter's [organ], attempting to pick up the organ through the context menu instead interacts with Kade Hunter. 
this does not happen if their mouseover name is not exactly as it is on the organ. if they are Unknown or wearing the wrong ID it will pick up the organ normally

https://user-images.githubusercontent.com/93528889/168447749-b95b66b9-3548-4414-9c47-1d965f76da58.mp4

**Comment by soleilan** [comment] 2023-03-02 23:54
dupe of #8674

**Closed by soleilan** 2023-03-02 23:54 UTC
Labels: C-Bug
