### ISSUE TITLE
Bug while laying cable on Oshan Laboratory

### ISSUE THREAD

**Issue by Glamurio** [goonstation/goonstation#10878] opened 2022-09-18 14:50 UTC
### Labels

[BUG][MAJOR]

### Description

When trying to lay cable while moving, it's not doing so at all. 

### Steps to reproduce

1. Walk out into the ocean.
2. Interact with held cable to "Lay while moving"
3. It is not "laying while moving" at all.

### Expected Behavior

When interacting with a cable, it should lay cable while moving

### Additional Information & Screenshots

This bug specifically happened on Oshan Laboratory. It makes playing Engineer extremely frustrating and makes the process take a lot longer, especially when hotspots are far away.

**Comment by nefarious6th** [comment] 2022-09-18 16:12
Duplicate of #10877

**Closed** 2022-09-19 08:49 UTC
Labels: C-Bug, P-Major
