### ISSUE TITLE
Supernorn walls now impossible to distinguish in mapeditor

### ISSUE THREAD

**Issue by comradef191** [goonstation/goonstation#4742] opened 2021-05-15 14:18 UTC
[BUG][MAJOR]

**Describe the bug**
Since the introduction of Smooth walls, it has been impossible to easily distinguish all 5 types of Supernorn walls.
This is due to the fact all Supernorn walls now use the mapeditor sprite for standard walls.

**To Reproduce**
1. Open any version of the code later then b248e5c using a mapeditor
2. Place down a `/turf/simulated/wall/auto/reinforced/supernorn` tile
3. Place down a `/turf/simulated/wall/auto/supernorn` tile

**Expected behavior**
To be able to visibly distinguish between both wall types.

**Screenshots**
![image](https://user-images.githubusercontent.com/62987296/118364504-9682ba80-b590-11eb-9106-162f66bd2e93.png)
![image](https://user-images.githubusercontent.com/62987296/118364509-9a164180-b590-11eb-877c-88c7a38d6a27.png)

**Additional context**

**Comment by nefarious6th** [comment] 2021-05-15 19:51
Duplicate of #4535

**Closed** 2021-05-15 22:23 UTC
Labels: bug, bug - major
