### ISSUE TITLE
Owlry gets covered in acid on nadir

### ISSUE THREAD

**Issue by NibChocolateeny** [goonstation/goonstation#20133] opened 2024-07-30 03:25 UTC
### Labels

[BUG][MAPPING]

### Description

if you do not close airlock on inside part of owlry if map is nadir and you go to owlry and back to nadir and back to owlrey, then acid flood in the enterance hallway, and allso on the bus plane

### Steps to reproduce

1. the map must be on nadir
2. go to john bus in the lower down ecspape area
3. take buss to owlerey
4. open air door lock to inside of owlrey (i think it is needed)
5. go bacck to station
6. go back to owelry
7. ow! ow! acid in hall!

### Expected Behavior

no acid! it is SPACE in owlry! not acid sea! it is no immerssion...no immersion in acid!

### Additional Information & Screenshots

it was very not nice :<
![Goonstation 4 Roleplay Sylvester Nadir Extraction Site 2024-07-28 200954](https://github.com/user-attachments/assets/a43b9993-8161-4104-9442-56badf338afb)
![Goonstation 4 Roleplay Sylvester Nadir Extraction Site 2024-07-28 202556](https://github.com/user-attachments/assets/15723a54-cc92-4261-a3f2-4dc11e744039)
i did a try on "local" and i saw it happen in same way - only if owlerey door is open, not splaceplane door
![Nadir Extraction Site 2024-07-29 232342](https://github.com/user-attachments/assets/877abc85-d832-444d-bd9f-baddcb64b642)

**Comment by NibChocolateeny** [comment] 2024-07-30 12:53
it has been seen another time: #15040

**Comment by Kubius** [comment] 2024-07-30 18:07
Appears to indeed be duplicate of #15040.

**Closed by Kubius** 2024-07-30 18:07 UTC
Labels: C-Bug, A-Mapping
