### ISSUE TITLE
Genetics unable to buy more materials

### ISSUE THREAD

**Issue by exydis01** [goonstation/goonstation#7608] opened 2022-02-24 18:52 UTC
### Labels

[BUG]

### Description

When clicking the dollar sign button to buy more materials nothing pops up to let you buy them

### Steps to reproduce

1. click button and notice nothing happening

### Expected Behavior

click button and be able to buy materials

**Comment by exydis01** [comment] 2022-02-25 20:45
As a slight update to information on this if you go to the research tab and hit buy materials it still works just not the dollar sign button next the a gauge for how many materials you have

**Comment by nefarious6th** [comment] 2022-03-05 18:11
Duplicate of #7592

**Closed** 2022-06-12 05:30 UTC
Labels: bug
