### ISSUE TITLE
Changing into another form as changeling does not change your fingerprints

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#9458] opened 2022-07-04 13:39 UTC
### Labels

[MAJOR]

### Description

As a ling, your fingerprints remain the same when you change forms.

### Steps to reproduce

1. Be a ling
2. Check your prints
3. Change form and touch something
4. Check those prints

### Expected Behavior

If you impersonate someone you should impersonate fingerprints as well.

**Comment by nefarious6th** [comment] 2022-07-06 05:25
duplicate of #8997 ; that includes some of the other effects of the broken proc though, so this is good just for tabs on the isolated issue of how it affects changelings

**Closed** 2022-07-11 14:32 UTC
Labels: bug - major
