### ISSUE TITLE
Feeding ghosts

### ISSUE THREAD

**Issue by smitherzz6** [goonstation/goonstation#3911] opened 2021-03-06 02:42 UTC
[BUG]

**Describe the bug**
Can feed the ghosts

**To Reproduce**
1. Have Ectosensor Eye
2. Feed Ghost
3. Happy fed ghost

**Expected behavior**
Not to feed the ghost

**Screenshots**

**Additional context**

**Comment by Carbadox** [comment] 2021-03-06 09:58
Duplicate of #3916 
Will close this one since the other is more detailed

**Closed by Carbadox** 2021-03-06 09:58 UTC
Labels: bug
