### ISSUE TITLE
Afterlife bar  cigarettes

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#493] opened 2020-04-30 01:43 UTC
[BUG]

**Describe the bug**
Afterlife bar cigarette machine requires money. and its stock is not infinite.

**To Reproduce**
1. go to get cigarette
2. be sad it costs money
3. See error

**Expected behavior**
no money needed.

**Comment by MarkNais** [comment] 2020-04-30 01:51
Don't you spawn with money in your pockets? Just walk out and back in to get more money. Though that won't fix the stock issue.

**Comment by RSG250** [comment] 2020-04-30 03:09
miners dont spawn with money in pocket, as well as a few other jobs.

**Closed** 2020-06-12 00:16 UTC
Labels: bug

**Comment by pali6** [comment] 2020-06-12 00:20
not a bug
