### ISSUE TITLE
Space-bear-arm holding items

### ISSUE THREAD

**Issue by Emcee-Gore** [goonstation/goonstation#2777] opened 2020-11-22 09:37 UTC
[BUG]

**Describe the bug**
You can hold items in your space-bear-arm-hand.

**To Reproduce**
1. With a space-bear-arm you click on items and cannot pick them up; as the flavortext states.
2. BUT - when click-dragging the item onto you and you have the space-bear-arm-hand selected as your active hand; then the item you picked up by click-dragging onto yourself gets transported into the space-bear-arm-hand.

**Expected behavior**
To not accept this work-around.

**Comment by flappybatpal** [comment] 2022-05-21 07:44
Can't reproduce. Seems to have been fixed in the past.

**Closed by flappybatpal** 2022-05-21 07:44 UTC
Labels: bug, Needs Reproducing
