### ISSUE TITLE
Wood Sheet Requisition Issue

### ISSUE THREAD

**Issue by CrystalClover** [goonstation/goonstation#16217] opened 2023-10-02 22:54 UTC
### Labels

[BUG]

### Description

Wooden Sheets are only counted by number of stacks, rather than stack amount, so a Req requiring 8 planks will need 8 1 planks stacks instead of a single 8 plank stack

### Steps to reproduce

1. find requisition requiring wooden planks
2. place stack of 10 planks into crate
3. see that it only counts as 1 plank

### Expected Behavior

for however many planks are in the stack to be taken into account

**Comment by MeggalBozale** [comment] 2023-10-02 23:17
Nah I probably caused this ill fix it

**Comment by Kubius** [comment] 2023-10-02 23:18
Known issue, should be getting fixed in #16194

**Comment by UrsulaMejor** [comment] 2023-10-02 23:21
duplicate of #16192

**Closed by UrsulaMejor** 2023-10-02 23:21 UTC
Labels: C-Bug
