### ISSUE TITLE
When a ling gives control to a victim and the victim is in control at round end the original lings body is counted as destroyed.

### ISSUE THREAD

**Issue by Alexalmighty502** [goonstation/goonstation#5621] opened 2021-07-28 13:34 UTC
[BUG]

**Describe the bug**
see title

**To Reproduce**
1. Be eaten as a ling
2. be given control
3. keep control till the round ends
4. notice that the ling is counted as their body is destroyed and feel sorta bad about that

**Expected behavior**
They to be considered alive and well with the players eaten by both the master and the controller to be counted

**Screenshots**
i really should remember to take pictures huh?

**Comment by BatElite** [comment] 2021-07-28 22:11
Sounds like a duplicate of #2759? I'm not personally convinced that it'll matter whether the victim is in control at round end.

**Closed** 2022-09-24 05:06 UTC
Labels: C-Bug
