### ISSUE TITLE
Gene console crashes on me

### ISSUE THREAD

**Issue by MeggalBozale** [goonstation/goonstation#4737] opened 2021-05-15 03:17 UTC
[BUG]

**Describe the bug**
Other than that I was being a geneticist, I have NO clue. Really sorry, this was unexpected and abrupt to me. I was half sure at first that it was a fake but, but it was not.

**To Reproduce**
1. Mess around with the genetics console
2. I was clicking some buttons with someone in the scanner, i think...?
4. See error, hopefully

**Expected behavior**
The gene console does not crash.

**Screenshots**
[https://imgur.com/VmEY8W2](https://imgur.com/VmEY8W2)

**Additional context**
This was several rounds ago, sorry that I can't provide any specifics. I was able to close and reopen the gene console window to keep working, my game itself did not crash.

**Comment by Azrun** [comment] 2021-05-20 22:02
Additional Report:
https://discord.com/channels/182249960895545344/298827721604071425/845026175546163230

**Comment by Azrun** [comment] 2021-07-03 20:06
#5373 may be a duplicate of this

**Closed** 2022-09-24 05:05 UTC
Labels: C-Bug
