### ISSUE TITLE
screwing in an emergency light turns it on regardless of emergency status

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#11273] opened 2022-10-09 18:15 UTC
### Labels

[minor]

### Description

As title.

### Steps to reproduce

1. Take out an emergency light's bulb
2. Reinsert it

### Expected Behavior

For it not to turn on when emergency isn't active

**Comment by frawhst** [comment] 2022-10-09 18:18
You can take those bulbs out??????

**Comment by BatElite** [comment] 2022-10-09 20:20
You used to not be able to, but at some point that got changed I guess (#8986 apparently)

**Comment by Chatauscours** [comment] 2023-10-01 16:37
Duplicate of #9055

**Closed by Chatauscours** 2023-10-01 16:37 UTC
Labels: P-Minor
