### ISSUE TITLE
Armory Hammer doesn't deal bonus damage to airlocks

### ISSUE THREAD

**Issue by LadyBirb** [goonstation/goonstation#146] opened 2020-04-07 12:57 UTC
**Describe the bug**
The hammer's bonus damage isn't applying when it should, meaning it deals the same damage to airlocks as it does to spacemen (ie: not much)

**To Reproduce**
1. hit airlock with hammer
2. repeat 40+ times

**Expected behavior**
Should break airlocks in 8-12 hits.

**Additional context**
Haven't used the hammer myself, information comes from discord.

**Comment by Flaborized** [comment] 2020-04-07 13:36
Unable to reproduce, hammer broke airlocks in 10 hits and did a bunch of damage to myself when I hit myself with it on a local server (it has a high force but long delay between hits). Code looks fine to me as well? Has TOOL_CHOPPING so it looks like it Should Be Working Correctly.

**Comment by Gannets** [comment] 2020-04-07 15:36
I also saw some inconsistency in testing when I made them. I suspect it's less to do with the hammer and more that some doors have more health than others, though I haven't checked.

**Comment by ZeWaka** [comment] 2020-04-12 02:35
Resolved by #207

**Closed by ZeWaka** 2020-04-12 02:35 UTC
Labels: bug, unreproducible
