### ISSUE TITLE
RPG hand sprites do not have North direction

### ISSUE THREAD

**Issue by flappybatpal** [goonstation/goonstation#8214] opened 2022-04-15 09:07 UTC
### Labels

[BUG]

### Description

Missing RPG north hand sprite

### Steps to reproduce

1. Spawn /obj/item/gun/kinetic/rpg7
2. Face south then north, empty or loaded
3. See incorrect North sprite on the mob.

### Expected Behavior

Correct North sprite

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/70909958/163551096-dc43aebe-380b-4975-93a2-8debc6308c7b.png)

**Comment by Yellow-Mushroom** [comment] 2022-04-18 00:44
duplicate of #7894 , I will work on this soon

**Closed** 2022-04-19 02:47 UTC
Labels: bug
