### ISSUE TITLE
Borgs recharging drain apcs very quickly

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#13202] opened 2023-02-26 02:19 UTC
### Labels

[BUG]

### Description

Borgs, when recharging in a station, draing an apc very quickly, often resulting in the apc losing power

### Steps to reproduce

1. Be a borg
2. Run low on power
3. Go to a recharge dock
4. Enter it
5. Notice the room lose power shortly after entering the recharge dock

### Expected Behavior

For borgs recharging to not depower a room.

**Comment by nefarious6th** [comment] 2023-03-05 00:34
Duplicate of #13156

**Closed** 2023-03-17 02:52 UTC
Labels: C-Bug
