### ISSUE TITLE
The hover examine message for law modules is not right

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#8425] opened 2022-05-02 03:00 UTC
### Labels

[BUG]

### Description

Holding alt and hovering the cursor over a law module does not show the updated law for it.

### Steps to reproduce

1. Hold alt.
2. Move cursor over a law module with text set for it.
3. Wait for hover examine message to appear.

### Expected Behavior

For the hover examine message to show the text set for the law.

**Comment by amylizzle** [comment] 2022-05-03 18:03
Not actually sure this can be fixed without overhauling the tooltips stuff.

**Comment by TealSeer** [comment] 2023-10-22 00:28
Duplicate of #16287

**Closed by TealSeer** 2023-10-22 00:28 UTC
Labels: C-Bug
