### ISSUE TITLE
Water pipe disappears when water is added

### ISSUE THREAD

**Issue by WillHuff** [goonstation/goonstation#18005] opened 2024-02-18 07:25 UTC
### Labels

[BUG]

### Description

Whenever water is added to the water pipe, its sprite disappears.

### Steps to reproduce

1. Add water to a water pipe via clicking on a sink with it, or by transferring water from a different container.
2. The water pipe's sprite disappears from view.

### Expected Behavior

I expected the water pipe to remain visible, as water pipes are known to do.

### Additional Information & Screenshots

Water can be removed from the pipe while invisible, at which point it reappears. Items can be added to the hand where the pipe is, causing the pipe to be removed entirely. Weed can be added to the pipe while it is visible, but not while it is invisible.

**Comment by TealSeer** [comment] 2024-02-18 08:04
duplicate of #17993

**Closed by TealSeer** 2024-02-18 08:04 UTC
Labels: C-Bug
