### ISSUE TITLE
Medical Allergy Issue

### ISSUE THREAD

**Issue by Kamades** [goonstation/goonstation#2231] opened 2020-09-21 02:16 UTC
[BUG]

**Describe the bug**
Most medical allergies list as being Terpone, but are in fact for other medical chems.

**To Reproduce**
Have Medical Allergy.
Notice that in Medical Records, it says you are allergic to Terpone.
Instead, be allergic to Synthflesh or some other, unnamed chem that starts histamine production in you.

**Expected behavior**
To be allergic to Terpone, not Synthflesh.

**Screenshots**

**Additional context**
I've noticed this in a  few rounds, as well as it appearing everyone with a medical allergy has.. the same allergy (EG, lists everyone with Terpone, in fact, everyone is allergic to Omnizine.)

**Comment by zjdtmkhzt** [comment] 2020-09-21 02:32
I was unable to reproduce this, when testing locally.
I had a charcoal allergy and the medical records accurately reflected this.
After respawning myself my new character had a saline-glucose-solution allergy instead.
That also functioned correctly and was reflected correctly in the medical records.

I guess we should test this on the live server as well.

**Comment by Kamades** [comment] 2020-09-21 03:25
I've had it happen twice lately - both times, showing Terpone.  One time, I in fact had an Omnizine allergy, another time synthflesh.

Should I adminhelp if I see it happen again?

**Comment by zjdtmkhzt** [comment] 2020-09-23 04:03
Please check if it happens for you again in other rounds and let us know!
I'll try to see if my allergies work properly on the live server, if I remember.

**Comment by Tarmunora** [comment] 2020-09-30 23:16
issue related to traits being global

**Comment by Tarmunora** [comment] 2020-10-18 06:55
fixed by 2346

**Closed by Tarmunora** 2020-10-18 06:55 UTC
Labels: bug
