### ISSUE TITLE
A ling near instantly took control of host even though the removal of the parasite was done in less then 20 seconds

### ISSUE THREAD

**Issue by Alexalmighty502** [goonstation/goonstation#5832] opened 2021-08-29 13:14 UTC
[BUG]

**Describe the bug**
I was fighting Noot (Balarak#1693) at the end of the fight we were in medbay trying to remove his brain but he managed to headspider right before. He managed to quickly jump into the captain but due to us already being in the surgery area in medbay I was able to remove the headspider far earlier than the headspider should've been able to take control. I also successfully removed the parasite it dying immediately after removal like normal. I only learned later by a metagaming firebot that the surgery failed and Balarak was in control of the captain.

**To Reproduce**
1. Be a ling and headspider
2. jump into another person body
3. have the headspider quickly removed

**Expected behavior**
the ling to die when the parasite is correctly removed

**Screenshots**

**Additional context**
It was round 114610 if it helps in any way
https://goonhub.com/rounds/114610

**Comment by BatElite** [comment] 2021-08-29 19:30
Duplicate of #4551 and #5054

For what it's worth I think headspiders happen automatically on death, so that probably includes debraining

**Closed** 2022-06-12 05:37 UTC
Labels: bug
