### ISSUE TITLE
The 0kPa bug

### ISSUE THREAD

**Issue by trerri** [goonstation/goonstation#432] opened 2020-04-25 21:42 UTC
[BUG]

**Describe the bug**
TEG insists on pretending its cold loop inlet is 0kPa even though meters disagree. This has happened in some form every time I've played engineer on Kondaru. This causes engine performance to suck and sometimes produces brownouts in the engine output at about the 40 minute mark (the SMESes are obviously fine).

**To Reproduce**
1. Do a hellburn on Kondaru
2. Keep checking on the TEG's main interface
3. At some point the cold loop inlet will be 0kPa/fluctuating between -5 and 5kPa (yes it's also tied to negative pressure :byondood:)

**Screenshots**
Pure grief in an image.
![image](https://user-images.githubusercontent.com/63235460/80291508-49963100-874e-11ea-94bd-267542f666e6.png)

**Additional context**
I have been informed that "it can happen on any map, it's just more prominent on Kondaru because it has a huge combustion chamber". No idea what it means after the "any map" part.

**Comment by Azrun** [comment] 2020-10-30 23:33
I'll look into this.  May already be addressed by #2550 (if/when).

**Comment by Azrun** [comment] 2020-11-02 19:57
Evaluated on 4754f824 and fef4102f

Root Cause of Negative Absolute Pressure (BUG): 
- /datum/gas_mixture/proc/remove(amount) :: Quantized value could exceed molar quantity of corresponding gas, resulting in a negative molar quantity for gas giver.
- PR incoming!

Root Cause of Pressure Discrepancy:
- Readings on TEG interface are direct from circular which has two separate 200 unit air volumes (inlet/outlet). Readings from pressure sensor are for the pipe directly @ location which will likely have a different volume (70 + expansions). This discrepancy would be greatest at high temps (HELLBURN!!!) with LOW pressure (rupture because of HELLBURN!!!).
- Behavior is as designed .

**Comment by Azrun** [comment] 2020-11-23 04:18
@ZeWaka requesting closure because I don't know how to GitHub

**Closed** 2020-11-23 04:25 UTC
Labels: bug
