### ISSUE TITLE
[T-ray scanner visual] [BUG] [minor]

### ISSUE THREAD

**Issue by Darkinite** [goonstation/goonstation#5886] opened 2021-09-03 03:21 UTC
[BUG]

**Describe the bug**
If the scanner isn't turned off on the standard Hotbar and removed from the inventory the last place it scanned will continue to flash

**To Reproduce**
1. get a T-ray scanner
2. Turn on T-ray scanner on standard Hotbar
3. Walk around to see the pipes and wires
4. Stop on wire/pipe
5. put in the toolbox and throw away
6. walk away from the area 
7. See the pipe/wire still flashing

**Expected behavior**
The Glitch will flash the last area the T-ray scanner scanned

**Screenshots**
![T-Ray glitch](https://user-images.githubusercontent.com/29658789/131945634-9485deb9-ba47-4ed1-b750-143541abfb8e.png)

**Comment by stonepillars** [comment] 2022-07-13 23:53
Could not reproduce in current codebase, likely fixed in 5d29e6698f3a5ab9db8a51fe0825938a99b80f1e

**Closed** 2022-07-13 23:58 UTC
Labels: bug
