### ISSUE TITLE
TGUI chem dispenser error

### ISSUE THREAD

**Issue by virvatuli-gh** [goonstation/goonstation#3414] opened 2021-01-21 03:22 UTC
[BUG]

**Describe the bug**
Secondhand through logs, but it looks like if you cause fluoro acid smoke while the beaker is still inside the chem dispenser, it causes the beaker to melt if I was reading the logs right. It then completely broke the chem dispenser and gave a TGUI error for anyone who attempted to use it.

**To Reproduce**
1. insert beaker into chem dispenser
2. add fluoro acid and smoke powder to beaker
3. it goes whoosh
4. broken dispenser

**Expected behavior**
Beaker gets removed properly and doesn't break the dispenser (or maybe breaks it in a way that doesn't look like a bug)

**Screenshots**
![error](https://user-images.githubusercontent.com/68257280/105275618-c20b1080-5b6d-11eb-9bc0-2922c5e33d95.png)

**Comment by PrimeNumb** [comment] 2021-01-21 16:55
The acid smoke would not affect the beaker if it's inside the dispenser (and I could not reproduce this for the same reason).
Could probably just add some sanity checks in the dispenser code to make sure it doesn't happen again but it'd be interesting to know exactly how the beaker was deleted whilst inside a dispenser.

**Comment by Tarmunora** [comment] 2021-01-21 18:33
Something like a small nitroglycerin reaction might do it

**Comment by Tarmunora** [comment] 2021-01-21 19:26
Ok so the ***real*** issue here is that when you put a beaker into a dispenser, there's an intermediary step where it goes on the floor first. If you're in a cloud of fluorosulpheric acid, it melts when it enters the cloud, and then the qdeled beaker gets added to the dispenser, breaking things. I've applied a bandaid fix for this issue, but pacid smokes can probably break more things yet

**Closed by Tarmunora** 2021-01-21 19:26 UTC
Labels: bug
