### ISSUE TITLE
Springboard plays a splash sound regardless of where you land

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#11252] opened 2022-10-08 22:53 UTC
### Labels

[minor]

### Description

As title.

### Steps to reproduce

1. Go to a pool
2. Get on the springboard
3. When the crosshairs appear, aim outside the pool
4. get a splash sound effect anyway

### Expected Behavior

no splash if you don't land in water?

### Additional Information & Screenshots

Did this need to be a separate issue? Probably, not a lot of people touching sounds.

**Comment by TealSeer** [comment] 2023-10-22 00:21
Duplicate of #13796

**Closed by TealSeer** 2023-10-22 00:21 UTC
Labels: P-Minor
