### ISSUE TITLE
Hyposprays cannot be filled

### ISSUE THREAD

**Issue by 112358sam** [goonstation/goonstation#17393] opened 2023-12-19 05:01 UTC
### Labels

[BUG]

### Description

Hyposprays cannot be filled with reagents

### Steps to reproduce

1. Try to pour from a beaker of medical chems into a hypospray
2. nothing happens

### Expected Behavior

For the hypospray to fill with medical reagents

**Comment by TheTyrant25** [comment] 2023-12-19 06:10
duplicate of #17392

**Closed by TheTyrant25** 2023-12-19 06:10 UTC
Labels: C-Bug
