### ISSUE TITLE
Artifact borged saurian cant lose robot arms while 

### ISSUE THREAD

**Issue by Zergspower** [goonstation/goonstation#5546] opened 2021-07-17 21:10 UTC
[BUG]

**Describe the bug**
Artifact Borged person couldn't lose arms no matter who tried to remove them

**To Reproduce**
1. As a saurian (this is what happened to me , probably not a needed step) find and activate a borging artifact
2. after being borged, while trying to upgrade limbs  try wrenching your arms off.
3. Wrench arms off onto the ground, borg body still has arms
4. keep wrenching until infinity, slowly falling into a robotic paradox

**Expected behavior**
arms fall off

**Screenshots**

**Additional context**
upon being destroyed the duplicate arms disappear off the ground even from across the station ( the seem to teleport when you wrench them off)

**Comment by frawhst** [comment] 2021-07-17 21:55
Duplicate of #5209- this isn't exclusive to saurians or borger artifacts, it just Happens Sometimes. Oh, borgs.

**Comment by Zergspower** [comment] 2021-07-18 16:07
Well that makes it easier, just wanted to ensure I wasn't missing anything from the starting variables

**Comment by frawhst** [comment] 2021-11-15 11:28
fixed as of #5967

**Closed by frawhst** 2021-11-15 11:28 UTC
Labels: bug
