### ISSUE TITLE
Infused clothing not having expected behavior

### ISSUE THREAD

**Issue by alexeric123** [goonstation/goonstation#2637] opened 2020-11-09 16:39 UTC
**Describe the bug**
When I have 2 pieces of infused clothing on, i do not get the infused chemicals with the clothing on.

**To Reproduce**
Get a chemically infused clothing, put it on, the chemical does not get applied

**Expected behavior**
The Spessman having at least 1u in him of the chemical at all times with the clothing on.

**Additional context**
A mentor said he had a similar problem, told me to bugreport it,
material used was viscerite
chemical used was crime

**Comment by RSG250** [comment] 2020-11-09 16:44
this may possibly also be related to #2628

**Comment by Tarmunora** [comment] 2020-11-09 19:25
duplicate of #2628

**Closed by Tarmunora** 2020-11-09 19:25 UTC
