### ISSUE TITLE
Asymptomatic pancreatitis doesn't go away when replacing pancreas

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#14975] opened 2023-07-16 19:16 UTC
### Labels

[BUG]

### Description

Title

### Steps to reproduce

1. See someone with asymptomatic pancreatitis on their original organ. Think it was from AI turret lasers?
2. Cut it out
3. Replace with another organ (assuming its okay on health)
4. Replace with cyber organ

### Expected Behavior

For pancreatitis to go away

**Comment by pgmzeta** [comment] 2023-10-04 05:27
Dupe of https://github.com/goonstation/goonstation/issues/16107 - other issue has more detail

**Closed by pgmzeta** 2023-10-04 05:27 UTC
Labels: C-Bug
