### ISSUE TITLE
Showering when at 0% hygene doesn't remove stink lines

### ISSUE THREAD

**Issue by Gibuscode** [goonstation/goonstation#11571] opened 2022-10-24 19:47 UTC
### Labels

[BUG]

### Description

Showering when at 0% hygene doesn't remove stink lines.

### Steps to reproduce

1. Get stinky
2. Take a shower
3. Still stinky. Oh god.

### Expected Behavior

Expected to no longer have stink lines.

**Comment by thegrb93** [comment] 2022-10-24 20:39
Looks like the rancid status is responsible for the stink lines. Doesn't look like there's any way it could have failed unless there's a bug with RemoveEffect  https://github.com/goonstation/goonstation/blob/07739f7d044bb046114337c1c546bd447fa28bf6/code/modules/status_system/statusEffects.dm#L2065-L2081

**Comment by nefarious6th** [comment] 2022-10-30 13:58
Duplicate of #11512

**Closed** 2023-03-02 18:08 UTC
Labels: C-Bug
