### ISSUE TITLE
Eating speed is still abnormally slow, and you cannot eat at all while walking

### ISSUE THREAD

**Issue by TTerc** [goonstation/goonstation#4053] opened 2021-03-17 18:36 UTC
[BUG]

**Describe the bug**
Eating speed is still abnormally slow (it feels like you're eating only every 2nd bite) and you cannot eat at all while walking. It makes your sprite "jump" in a funny way but you don't eat at all

**To Reproduce**
1. Attempt eating
2. Attempt eating while walking around
3. Notice the problem

**Comment by Camryn-Buttes** [comment] 2021-03-17 21:31
@Superlagg

**Comment by geneva-breaker** [comment] 2021-03-26 14:52
closing this as the cause has been reverted and is being reimplemented correctly by someone else

**Closed by geneva-breaker** 2021-03-26 14:52 UTC
Labels: bug
