### ISSUE TITLE
Oshan  - telesci can send you to empty space level rather than trench on z5

### ISSUE THREAD

**Issue by COOLVAPE** [goonstation/goonstation#4717] opened 2021-05-14 07:06 UTC
[BUG]

**Describe the bug**
It's possible to teleport to an empty space z-level on oshan instead of the trench. Specifically, when i left the z level going north(?) i think, i ended up on another empty space z level. then i did the same thing, kept going, and ended up in a walled in area in the trench.

**To Reproduce**
1. Use telesci - I specifically used DWAINE commands, not the computer
2. Go to gps coordinates 59, 288, 9(station z was 4) in ai shell(probably same regardless of what you send)  - i used the send command to do this.
3. end up in an empty space z-level, rather than the trench.

**Expected behavior**
I would expect to end up in the corresponding location in the trench, not an empty space z-level.

**Additional context**
Didn't do anything other than these steps that I can think of.

**Comment by nefarious6th** [comment] 2021-05-14 07:18
Related to or a duplicate of #3186; but this one has steps to reproduce

**Comment by COOLVAPE** [comment] 2021-05-14 18:02
okay, this is definitely reproducible:
![image](https://user-images.githubusercontent.com/77637753/118310292-67027e00-b4bc-11eb-95d3-e98617091c93.png)
i went to a similar coordinate and ended up in space again, then repeated it with a different set of coordinates entirely and ended up in space again after that.

**Comment by COOLVAPE** [comment] 2021-05-14 19:47
realizing now that i was going to z6, and not z5. feel a little silly.

**Closed** 2021-05-14 21:10 UTC
Labels: bug
