### ISSUE TITLE
Strange Reagent ignores DNR status after brain transplant

### ISSUE THREAD

**Issue by Zamazenta** [goonstation/goonstation#5847] opened 2021-08-30 23:19 UTC
[BUG]

**Describe the bug**
Strange Reagent will revive players who have set DNR if you transplant their brain into another body after DNR has been set.
If the player sets DNR again after the brain transplant, they will not be revived.

**To Reproduce**
1. Have someone set DNR
2. Remove their brain and put it into a different body
3. Feed them strange reagent
4. Watch them come back to life

**Expected behavior**
The player will not be revived, as they had set DNR.

**Screenshots**
None

**Additional context**
None

**Comment by nefarious6th** [comment] 2022-07-29 05:11
duplicate of #8284

**Comment by ThatFiveGuys** [comment] 2022-08-04 03:08
Closing due to me liking the other one more

**Closed by ThatFiveGuys** 2022-08-04 03:08 UTC
Labels: bug
