### ISSUE TITLE
Combustion chamber is now generating less effective heat over char burns

### ISSUE THREAD

**Issue by mkrutov** [goonstation/goonstation#3480] opened 2021-01-26 19:33 UTC
[BUG]

**Describe the bug**
Disclaimer: I've started doing hellburns about 2 weeks ago, however this behaviour was confirmed by two other engineers.

3-5 days ago, setup which I did raised temperatures to low millions in under 30 minutes.
Right now, same setup is capping out at 8K C, and heat tranferred to hot loop is only around 2-3k C.

**To Reproduce**
1. Start combustion setup (tested various pressures for pump, various gas combinations).
2. Wait a little bit
3. See temperatures in combustion chamber in lines of 4-8k C, and temperature in pipes in lines of 2-3k C.
4. Kondaru is affected much more severely over Cogmap1. Kondaru's temperatures in pipes is 300-700k C.

**Expected behavior**
Don't know if this is expected behaviour for recent changes or not.

**Additional context**
This was confirmed to be a good setup with improper pump pressure by one of mentors (see neighbouring bug about blank messages - it was risen by that mentor). However, changing pressure to 90 as suggested by mentor, as well as starting system from scratch while having pressure at 90 at all times did not change anything.

**Comment by nefarious6th** [comment] 2021-01-26 19:38
I assume this is the expected behavior after the removal of hotspot pooling per #2808, which was merged exactly 2 days ago, so that accounts for the changes in the timeframe described above.

**Comment by mkrutov** [comment] 2021-01-26 19:49
That means that plasma burns now are less efficient than char burns. I could not get over 600kW of energy from plasma burn.

**Comment by mkrutov** [comment] 2021-01-26 20:00
(Disregard that, might be misunderstanding things.)

**Comment by Azrun** [comment] 2021-01-27 01:08
Pipe layout on Kondaru lends itself to a bit of a cold-spot right before hot-loop inlet unfortunately, as I found looking into #3481. 😦 

Gas mixture and pressure will be more important as you will have to use a more of it instead of the minuscule amounts pre-#2808.  In regards to Hellburns I'd recommend playing with creating burns in the pipes and/or looking at the new mineral in #2808. 

Leaving open as "top" end may need to be tweaked a bit as I'd expect better "performance" on Kondaru which makes me question overall chamber temp.

**Comment by TTerc** [comment] 2021-01-27 10:05
doesn't it also affect toxins and TTVs/canbombs? since you really need very high temperatures in case of the latter

**Comment by mkrutov** [comment] 2021-01-27 10:24
Azrun,

Problem with performance is not limited to Kondaru

Consider following scenario

Charburn is creating around 2k C temperatures which nets over 2MW

Hellburn is creating 8k temperature, which heats gas to something around 2-3kC, which for reasons I don't understand only nets sub 1MW (I've had 2.2k C temps and 300-350 kW gen yesterday).

**Comment by mkrutov** [comment] 2021-01-27 10:25
Also,
 We've tried playing around with Molitz Beta, and can not seem to figure it out yet.

**Comment by Azrun** [comment] 2021-01-28 00:58
@TTerc definitely impacts Toxins before the gas is in the can.  Molitz Beta will also be highly valuable to Toxins for you know... _science_.

@mkrutov Its going to be a function of gas mix of the medium, molar quantity, temperature, (and pressure). Depending on how much gas is on the inlet side you can leverage the blowers to squeeze out more power.
I understand it isn't limited to Kondaru, that was one where I saw the layout cause issues as large quantity of a cooler gas was sitting at the inlet while HOT wonderful gas was slowly trickling in from the passive gate.

I'm sitting on some changes to increase the likelihood of Moltz Beta spawning as well as increase the drop count but I'm interested in how the station is able to work together to acquire and use it.

Additionally looking at scaling up the soft-cap temperature for hotspots.  Which I'm not a super fan of, but I do want to give burn chamber an edge over chambers across the board which seem to be map by map issue 😕. We should be rewarded for tending the flame. 🔥

**Comment by q009** [comment] 2021-02-19 22:03
I'm managing to squeeze out over 50k C in the combustion chamber with molitz beta. Making over 20 MW.
I don't know how much more is actually possible, at that point I'm really fighting the pressure in the hotloop, but either way, you can definitely get a lot more power with the combustion chamber than just using the furnaces.

**Comment by Azrun** [comment] 2021-02-20 00:11
Issue addressed, chamber temps raised to allow for gas temps over 4k.

**Closed by Azrun** 2021-02-20 00:11 UTC
Labels: bug
