### ISSUE TITLE
Persistent bleeding without shrapnel

### ISSUE THREAD

**Issue by ryebek** [goonstation/goonstation#161] opened 2020-04-08 07:06 UTC
**Issue:**
When bleeding, you'll randomly get the message "Your bleeding stops!" multiple times, and not have the indicator of bleeding, but your examine text will read it as being there,  as will health analyzers. You create blood splashes on the floor still, but no actual blood loss occurs.

**Steps to reproduce the behavior:**
1. Cut off very syndicate hat arm you paid 90k spacebux for
2. Put it on
3. Use mender on self to heal bleeding
4. "Phantom bleeding" occurs

**Expected behavior**
The styptic clears the bleeding and examine text doesn't show as bleeding.

**Screenshots**
Uploaded this after roundend, so I can only post chat logs.
https://imgur.com/rp3bPDV - Health analyzer scan
https://imgur.com/wS9GyBH - Chat says the bleeding stopped, but the examine text says otherwise

**Additional context**
Urs was auctioning off a mystery item arm for spacebux, and removed my arm, before replacing it with the very syndicate hat. I've also had this "phantom bleeding" happen to me before, but it seems a bit random with what actually causes it.

**Comment by ZeWaka** [comment] 2020-04-08 07:14
Duplicate of #143

**Closed by ZeWaka** 2020-04-08 07:14 UTC
Labels: bug
