### ISSUE TITLE
Some AI/Borg windows don't have exits

### ISSUE THREAD

**Issue by DicksonOrmus** [goonstation/goonstation#2278] opened 2020-09-27 10:53 UTC
[BUG]

You can not close certain windows in the UI as ai/borg

![toxiborg](https://user-images.githubusercontent.com/63312059/94363134-cb83e080-0085-11eb-980f-f46c7818dcda.png)

**Comment by Carbadox** [comment] 2021-01-16 12:10
Could not reproduce.

**Comment by amylizzle** [comment] 2022-07-15 13:19
This is an issue with CHUI windows not rendering properly, and can be fixed by either refreshing the browser window, or toggling the Chui's Custom Window Frames option under Game->Interfaces.

Closing, since it's a client issue and we're moving away from CHUI anyway.

**Closed by amylizzle** 2022-07-15 13:19 UTC
Labels: bug
