### ISSUE TITLE
Microlite Jetpack icon in examine is weird

### ISSUE THREAD

**Issue by trollbreeder** [goonstation/goonstation#11680] opened 2022-10-29 10:39 UTC
### Labels

[BUG][Minor][Sprites]

### Description

The microlite jetpack (oxygen)'s icon shows what seems to be its spritesheet

### Steps to reproduce

1. Wear a microlite jetpack, or find someone who is wearing one
2. Examine yourself or the jetpack-wearing person
3. Look at the icon of the jetpack in the examine text

### Expected Behavior

I expected to see a sprite of the jetpack itself, rather than the entire dmi file it's in.

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/25937686/198825716-e8e46d36-303e-4280-bfba-8bd153cb2e63.png)
![image](https://user-images.githubusercontent.com/25937686/198825745-a24a5ffd-1ed9-4531-af73-cbfdfea927ce.png)

**Comment by nefarious6th** [comment] 2022-10-30 13:54
Duplicate of #11368

**Closed** 2023-10-22 00:19 UTC
Labels: C-Bug, P-Minor
