### ISSUE TITLE
Go board was bug and cant play 

### ISSUE THREAD

**Issue by FronkyGeniuZ** [goonstation/goonstation#19488] opened 2024-06-13 09:15 UTC
### Labels

[BUG]

### Description

The go board UI bug cant play

### Steps to reproduce

1. click on the go board with bare hand

### Expected Behavior

can play it normally 

### Additional Information & Screenshots

other people try it too the result was the same as me.
<img width="695" alt="image" src="https://github.com/goonstation/goonstation/assets/153364397/855081a0-6f09-4f2f-9ca4-d790d4840a7b">

**Comment by TealSeer** [comment] 2024-06-13 17:35
Duplicate of #19111

**Closed by TealSeer** 2024-06-13 17:35 UTC
Labels: C-Bug
