### ISSUE TITLE
Food duplication visual glitch

### ISSUE THREAD

**Issue by Saicchi** [goonstation/goonstation#17303] opened 2023-12-12 09:36 UTC
### Labels

[BUG]

### Description

Duplicating food using plates

### Steps to reproduce

1. Put food in one plate
2. Drag food to another plate
3. Food duplicates

### Expected Behavior

Food item goes to another plate

### Additional Information & Screenshots

Replicable as a cyborg. Food shoes on the plate but it can't be eaten or removed, putting it in an oven also wont duplicate the item, but if the original one is nearby it gets thrown into it.

**Comment by gear-space** [comment] 2023-12-12 14:49
Duplicate of #17303 - click dragging food between plates/trays for any mob type is not working as expected.

**Closed by gear-space** 2023-12-12 14:49 UTC
Labels: C-Bug
