### ISSUE TITLE
Light bulb duplication by deconstructing and reconstructing light fixtures

### ISSUE THREAD

**Issue by MyNameIsRomayne** [goonstation/goonstation#20389] opened 2024-08-22 18:40 UTC
### Labels

[BUG] [MINOR]

### Description

Rebuilding a fixture which had no bulb when deconstructed places in a new bulb regardless

### Steps to reproduce

1. Take light bulb out of fixture
2. Turn off lights (doesnt cause bug, just needed for step 3)
3. Unscrew fixture with a screwdriver
4. Turn lights on (optional, doesnt matter)
5. Replace fixture

### Expected Behavior

Replaced with no lightbulb

### Additional Information & Screenshots

![dreamseeker_eBtHP6nYj7](https://github.com/user-attachments/assets/8b28af47-527e-474d-b2ac-45bede73c91e)

**Comment by soleilan** [comment] 2024-08-23 10:36
duplicate of #18872

**Closed by soleilan** 2024-08-23 10:36 UTC
Labels: C-Bug, P-Minor
