### ISSUE TITLE
Chanegelings Fail objectives if not in control when the shuttle reaches centcom

### ISSUE THREAD

**Issue by Supermichael777** [goonstation/goonstation#6189] opened 2021-10-06 01:20 UTC
Was a hivemind member. Master handed off control to AFK near EOR. Brought master body to centcom. Master registered as body destroyed. Round ended ~9:15 PM EDT 9/5/21  on nightshade 1.

**Comment by nefarious6th** [comment] 2022-07-29 05:52
duplicate of #5621

**Comment by TheTyrant25** [comment] 2023-08-04 07:20
duplicate of #5621 and presumably fixed by #13571

**Closed by TheTyrant25** 2023-08-04 07:20 UTC
Labels: C-Bug, P-Minor, A-Medal, A-Gamemodes, A-Status-Effects, A-Player-Actions
