### ISSUE TITLE
Can use sponge to clean UI elements

### ISSUE THREAD

**Issue by Stushcinta** [goonstation/goonstation#10750] opened 2022-09-10 10:53 UTC
### Labels

[BUG]

### Description

Can use sponge to clean UI elements

### Steps to reproduce

1. Grab a sponge
2. Fill sponge with Water
3. Click sponge on Flashlight/Oxygen buttons

### Expected Behavior

I didn't expect the sponge to work on UI elements

### Additional Information & Screenshots

I don't think this is a really important bug but i just thought i'd point it out.

![spongebug](https://user-images.githubusercontent.com/17263548/189480080-131c7b0e-bfbf-411c-a120-95186586492e.PNG)

**Comment by avimour** [comment] 2022-09-11 17:33
duplicate of #9526!

**Closed by avimour** 2022-09-11 17:33 UTC
Labels: C-Bug
