### ISSUE TITLE
New style intercoms on Manta bridge look positioned wrong

### ISSUE THREAD

**Issue by Kyle2143** [goonstation/goonstation#1106] opened 2020-06-15 08:54 UTC
[BUG]

**Describe the bug**
The intercoms don't really fit the tiles they appear on as well as the old intercoms did. Currently their pixel_y var is 24, I moved the one on the far left to 36 and I think it looks a bit better, but still kinda off. Either the intercoms need to be changed or the tiles they sit on.

**Screenshots**
![image](https://user-images.githubusercontent.com/9010341/84637678-fde94380-aec3-11ea-8944-871c3827e84f.png)

**Additional context**

**Comment by MarkNais** [comment] 2020-06-30 09:18
That leftmost intercom was in-line with the rest in the recent round I played. Also, duplicate of pinned issue #927

**Closed** 2020-06-30 09:19 UTC
Labels: bug - trivial, duplicate, good first issue, mapping
