### ISSUE TITLE
Microbombs seem to not delete/dispose after explosions.

### ISSUE THREAD

**Issue by Momoberry** [goonstation/goonstation#10949] opened 2022-09-22 02:58 UTC
### Labels

[BUG] [MAJOR]

### Description

After a hunter exploded, I was able to steal their microbomb and implant it in myself. After using it for a gimmick when I rolled sleeper, I too exploded and the microbomb fell out of me onto the ground.

### Steps to reproduce

1. boom.
2. boom chip on ground.

### Expected Behavior

I mean personally it's kind of fun, but I think they're supposed to be disposed of after explosion.

**Comment by nefarious6th** [comment] 2022-09-22 04:05
Duplicate of #10946

**Comment by Momoberry** [comment] 2022-09-22 05:04
> Duplicate of #10946

Just flip the 9 at the end around and pretend it's my PR

**Closed** 2022-09-22 22:03 UTC
Labels: C-Bug, P-Major
