### ISSUE TITLE
Fluorosulfuric acid doesn't not melt off worn internals when deployed with smoke powder

### ISSUE THREAD

**Issue by isaacashtox** [goonstation/goonstation#1907] opened 2020-08-23 06:35 UTC
[BUG]

**Describe the bug**
Fluorosulfuric acid doesn't melt internals off people when deployed with smoke powder no matter the amount of acid present.

**To Reproduce**
1. Mix smoke powder and fluorosulfuric acid in beaker. Wiki states acid only needs 9 units to melt internals with 100% chance.
2. Detonate and watch the smoke melt other nearby objects on the floors but not your internals.

**Expected behavior**
Any smoke with at least 9 units of fluorosulfuric acid should melt your internals off 100% of the time.

**Screenshots**
*poorly scribbled image of a beaker*

**Additional context**
Fluorosulfuric acid deployed with aerosol propellant works normally. Pouring the acid on yourself manually also works fine. Even a beaker with 10 units of smoke powder, 90 units of acid will not melt your internals.

**Comment by PrimeNumb** [comment] 2020-08-28 22:03
Not a bug, as explained above. Melts internals correctly if units of acid exceeds the minimum of **10u**. Closing this.

**Closed by PrimeNumb** 2020-08-28 22:03 UTC
Labels: bug
