### ISSUE TITLE
Gem stones are very good for windows 

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#6901] opened 2021-12-12 18:18 UTC
### Labels

[BUG]

### Description

gemstones arent translucent or whaterver any more so you cant see thru windows made from them

### Steps to reproduce

1. make sheets out a of a gem stone
2. make window
3. be sad

### Expected Behavior

i want to be able to see thru my fancy windows

**Comment by TobleroneSwordfish** [comment] 2021-12-12 18:53
duplicate of #6761 which was also submitted by you

**Comment by Zonespace27** [comment] 2021-12-12 18:54
Dupe of #6761

**Closed by Zonespace27** 2021-12-12 18:54 UTC

**Comment by RSG250** [comment] 2021-12-12 19:20
wow i didnt realize i already did a report
