### ISSUE TITLE
Cloning lets the mime break their vow of silence 

### ISSUE THREAD

**Issue by trollbreeder** [goonstation/goonstation#12269] opened 2022-12-02 16:59 UTC
### Labels

[BUG][MAJOR][PLAYER ACTIONS]

### Description

After a mime gets cloned, their enforced vow of silence is broken, letting the mime talk and scream and laugh.

### Steps to reproduce

1. Be a mime. (Observe how you cannot talk)
2. Die (in a way that preserves your body)
3. Get cloned.
4. (Potentially optional step? Not sure. Scoot on over to genetics and get scrambled genes. Mutadone might also work?)
5. Speak! Let the WORLD hear your WORDS!
6. You are not prevented from speaking. Your vow is broken! Shameful mime.

### Expected Behavior

Mime should shut up

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/25937686/205343691-3668e617-5df1-4092-b840-8ef9b225bf88.png)
![image](https://user-images.githubusercontent.com/25937686/205344251-8f1e024e-4b44-438b-9d51-d2f0554edacf.png)
This was definitely a real Mime, as they couldn't scream earlier in the round:
![image](https://user-images.githubusercontent.com/25937686/205344461-dba0b696-fc7f-4ed5-9f28-b62a4ad7caa4.png)

**Comment by trollbreeder** [comment] 2022-12-03 00:39
update: skimmed some conversation from the mime.
i think you might need to have the mime's genes scrambled in order to break the vow.

**Comment by TobleroneSwordfish** [comment] 2022-12-03 13:09
nope, pretty sure cloning just straight up removes it

**Comment by nefarious6th** [comment] 2022-12-04 22:08
Duplicate of #11935

**Comment by thegrb93** [comment] 2022-12-07 18:05
I can take another stab at this this weekend when I have access to a debugger

**Comment by ZeWaka** [comment] 2023-02-02 00:02
duplicate of #11935

**Closed by ZeWaka** 2023-02-02 00:02 UTC
Labels: C-Bug, P-Major, A-Player-Actions
