### ISSUE TITLE
Action bars are broken

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#12120] opened 2022-11-22 23:35 UTC
### Labels

[BUG]

### Description

They don't show up, their icons still do

### Steps to reproduce

1. Perform action bar action
2. See no action bar

### Expected Behavior

I expected action bars

**Comment by nefarious6th** [comment] 2022-11-23 00:28
Duplicate of #12118

**Closed** 2022-11-23 01:03 UTC
Labels: C-Bug
