### ISSUE TITLE
Antag critter can fly strelka pod

### ISSUE THREAD

**Issue by Tiggersaurus** [goonstation/goonstation#1421] opened 2020-07-09 22:33 UTC
[BUG]

**Describe the bug**
While observing someone as lil space spider, they were able to enter and control the Strelka pod. Not sure this is intentional behaviour?

**To Reproduce**
1. Become lil space spider through antag critter event.
2. Board the Strelka.
3. Pewpew people with lasers.

**Expected behavior**
I know they have many legs but for them not to fly it is expected.

**Comment by Tarmunora** [comment] 2020-07-10 02:10
Any mob can pilot pods unless specifically exempt (ghostcritters I believe are)

**Comment by PrimeNumb** [comment] 2020-07-12 02:41
This is not a bug - like yass mentioned it's something any mob can do. I double checked with mbc and it's working as intended.

Closing this.

**Closed by PrimeNumb** 2020-07-12 02:41 UTC
Labels: bug
