### ISSUE TITLE
Ghost drones & Loading Chutes

### ISSUE THREAD

**Issue by Momoberry** [goonstation/goonstation#5861] opened 2021-09-01 05:44 UTC
[BUG] [MINOR]

**Describe the bug**
If you float over a loading chute just as it starts opening up again, you are able to continue floating past it but your camera will get caught by the loading chute and get stuck inside it until you go through it for a second time.

**To Reproduce**
1. Activate loading chute once.
2. Right as it starts its animation to open up, float over it and past it.
3. Your camera should be stuck in the loading chute now.
4. Wait till it reopens again and go through a 3rd washing cycle to fix your camera.

**Expected behavior**
You fall in, body and soul.

**Comment by BatElite** [comment] 2021-09-01 08:49
Probably the same thing as #4561 / $4844

**Comment by frawhst** [comment] 2022-03-10 02:49
dupe of #7557

**Closed by frawhst** 2022-03-10 02:49 UTC
Labels: bug, bug - minor
