### ISSUE TITLE
Deploying to a shell as AI causes connection problems

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#13353] opened 2023-03-11 23:15 UTC
### Labels

[BUG]

### Description

Deploying to a shell, specifically the round ones, will occasionally cause a reconnect

### Steps to reproduce

1. Be AI
2. Try to deploy to a shell
3. Connection issue

### Expected Behavior

For a connection issue to not happen when deploying to a shell

**Comment by flappybatpal** [comment] 2023-04-08 14:02
Duplicate of https://github.com/goonstation/goonstation/issues/8688

**Closed by flappybatpal** 2023-04-08 14:02 UTC
Labels: C-Bug
