### ISSUE TITLE
Wraith can click drag move items while incorporeal

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#11931] opened 2022-11-11 20:33 UTC
### Labels

[BUG]

### Description

Wraith can move items around by click dragging them

### Steps to reproduce

1. Be wraith
2. Be incorporeal
3. Click drag items from one tile to another

### Expected Behavior

I expected mob/living/intangible to not allow this, apparently it does

**Comment by Bartimeus973** [comment] 2022-11-12 02:01
That was a thing before the transition to intangible. Im reasonably sure this is intended behavior?

**Comment by MetricDuck** [comment] 2022-11-13 22:11
This is just their click-drag tk, unless I'm reading it properly

#4768

**Comment by Bartimeus973** [comment] 2022-11-14 21:48
I'll close this considering it's very likely intended, as there is specific code supporting this. Do re-open it if it isnt!

**Closed by Bartimeus973** 2022-11-14 21:48 UTC
Labels: C-Bug, S-Possibly-Intended
