### ISSUE TITLE
Ghost Critters can speak normally to others inside of a vehicle

### ISSUE THREAD

**Issue by RelentlessGarbage** [goonstation/goonstation#13381] opened 2023-03-17 21:22 UTC
### Labels

[BUG]

### Description

When riding in a vehicle as a ghost critter, speaking allows non-critter players riding in the same vehicle to hear and understand what you're saying

### Steps to reproduce

1. Be a ghost critter
2. Enter a vehicle that can hold more than one passenger
3. Have another passenger either enter or be present in the vehicle
4. Speak normally - the other player in the vehicle will be able to see your maptext speech

### Expected Behavior

I expected not to have understandable speech in any situation when playing as a ghost critter. (Not that I mind...)

### Additional Information & Screenshots

This has been verified to work with both civilian pods and minisubmarines. I expect it to work with all other kinds of vehicles as well.

The accounts of the other players I have done this with say that they cannot see the maptext (i.e. hear you as a ghost critter) if they leave the vehicle. Conversely, they cannot hear your speech if you are outside of the vehicle and they are in it (although this is as expected).

A second point of note is that, if a vehicle has an intercom/speaker system, the ghost critter can use it, and players outside of the vehicle can hear and respond to what you say.

**Comment by soleilan** [comment] 2023-03-17 21:44
dupe of #10916

**Closed by soleilan** 2023-03-17 21:44 UTC
Labels: C-Bug
