### ISSUE TITLE
Dwarfism Visual Bug

### ISSUE THREAD

**Issue by Iq2Gamer** [goonstation/goonstation#7215] opened 2022-01-19 03:50 UTC
### Labels

[BUG]

### Description

Scanning someone with the handheld genetic analyzer will reset the visual dwarfism of the sprite for everyone, negating the trait.

### Steps to reproduce

1. Get someone with an active dwarfism trait.
2. Get a handheld genetic analyzer. (the one that Geneticist start the game with.)
3. Left click the genetic analyzer in your hand on the other person with dwarfism. 
4. Watch as the person return to normal size.

### Expected Behavior

Using the genetic analyzer should scan the person but not disable the visual of the sprite for those that have the gene active.

**Comment by Vaskritaya** [comment] 2022-01-19 23:36
Duplicate of #6770

**Closed** 2022-01-21 20:23 UTC
Labels: bug
