### ISSUE TITLE
MULEbot behavior broken

### ISSUE THREAD

**Issue by nefarious6th** [goonstation/goonstation#4057] opened 2021-03-18 00:14 UTC
[bug]
**Describe the bug**
Normal, un-hacked MULEbots act like hacked MULEbots that can be moved through, have no speed safety on them, and allow for people to ride them. This applies to MULEs with set home destinations, brand new ones ordered from QM, and ones without set home destinations.

**To Reproduce**
1. Try to enlist the help of MULEbot
2. Accidentally move through the bot
3. Load a crate or yourself
4. Set destination on PDA and go speeding off

**Expected behavior**
MULEbot to be cooperative, slow, and unable to be moved through by humans or take humans as cargo! Didn't test running people over because that would Be Bad

**Additional context**
Tested on local server and on Classic 1 server; same behavior on both. Checked variables on local and none were modified.

**Comment by penny64** [comment] 2021-03-18 00:34
There's actually no restrictions about humans as cargo, the functionality exists but it's not turned on.

**Comment by nefarious6th** [comment] 2021-03-18 00:49
It's turned on automatically on non-hacked MULEbots is the problem

**Comment by penny64** [comment] 2021-03-18 00:56
That's what I mean, the rest is a bug but humans are supposed to be loadable by default

**Comment by nefarious6th** [comment] 2021-03-24 21:34
Looking at this more; the tempermental pathing is also related to this. Something is wrong with the access level allowed on MULEbot. In mulebot.dm it's set to have Captain access, but on testing it refusesto path because it doesn't have the ability to access the doors into/out of QM and reads itself as being trapped. Works fine if you open the doors and then send it though, so it's a problem with the bot access or the bot access being overidden.

**Comment by zjdtmkhzt** [comment] 2021-07-02 12:36
I believe this was fixed in [44a1ff8](https://github.com/goonstation/goonstation/commit/44a1ff8010db0379da130adc27969b723cc42942).

**Comment by penny64** [comment] 2021-07-02 17:29
It was not, they still run around screaming like maniacs and running everyone over

**Comment by zjdtmkhzt** [comment] 2021-07-02 21:47
The part about humans being able to be put on by default is normal though, that's not a bug?
Them avoiding humans seemed to work fine for me.

I am not sure what you mean by "screaming like maniacs"?

**Comment by penny64** [comment] 2021-07-02 21:49
Oh sorry that's just what they do in fast mode, they have trouble pathfinding because they're so fast and they stop and complain and then find a path and then do it all over again. That's not really a bug, but, it's hacked

However  I was looking and I think another PR actually might have fixed it

**Closed** 2022-01-20 21:00 UTC
Labels: bug
