### ISSUE TITLE
Half of shuttle left and half stayed

### ISSUE THREAD

**Issue by TheColorCyan** [goonstation/goonstation#15252] opened 2023-08-05 16:41 UTC
### Labels

[BUG]

### Description

Title

### Steps to reproduce

1. Go on shuttle like nothing
2. See half of shuttle just dissapear
3. ???

### Expected Behavior

People were saying that some were in centcom but round didnt end. I got teleported to some space with nothing as well like after 1 minute.

### Additional Information & Screenshots

<img width="1183" alt="moreweirdness" src="https://github.com/goonstation/goonstation/assets/109153765/a8eb26eb-329a-4e29-8844-059fd1c1bde7">

![whattheheck](https://github.com/goonstation/goonstation/assets/109153765/04b85747-590c-4ac3-ae8e-83bd0a67ebd3)

![guhwhat](https://github.com/goonstation/goonstation/assets/109153765/d238373e-0a17-4dfb-b691-01ed3c048fdb)

**Comment by TheColorCyan** [comment] 2023-08-05 16:45
there were also nanites maybe its related to it

**Comment by unfunnyperson** [comment] 2023-08-06 14:43
pretty sure this was fixed by 129edb8

**Comment by TheTyrant25** [comment] 2023-08-08 08:02
going to assume this was fixed in the same day that all of the weird prefab loading glitches happened

**Closed by TheTyrant25** 2023-08-08 08:02 UTC
Labels: C-Bug, S-Needs-Reproducing

**Comment by flappybatpal** [comment] 2023-08-08 08:11
This round had infinite loops going on so I believe it was caused by that generally locking up processes, not other code, or bugs.

**Comment by TheTyrant25** [comment] 2023-08-08 08:26
that would make sense
If it was the in the rounds with the faulty cog1 engine and other similar rounds with faulty prefab loading, then I think it might have been fixed. As such this is kinda un reproducible
