### ISSUE TITLE
Sleeper agent call Takes a long time

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#5690] opened 2021-08-06 15:52 UTC
[BUG]

**Describe the bug**
When the sleeper agent call happened, it took several minutes for each number to be called out.

**To Reproduce**
1. Wait for a sleeper agent event to occur
2. Notice the lethargic callout

**Expected behavior**
I'm pretty sure the event doesn't even take a minute to go through the number callouts, let alone several.

**Screenshots**

**Additional context**
Not sure if the recent change to the audio for the callout resulted in this, or if the callout was slowed due to the server being busy

**Comment by flappybatpal** [comment] 2021-08-06 15:53
Duplicate of #5685

**Closed by flappybatpal** 2021-08-06 15:53 UTC
Labels: bug
