### ISSUE TITLE
Unstable mutagen not penetrating skin. 

### ISSUE THREAD

**Issue by DicksonOrmus** [goonstation/goonstation#360] opened 2020-04-21 13:10 UTC
[BUG]

Unstable when you dump it on people isn't showing in their system.   I have tested it three times.

**Comment by Gerhazo** [comment] 2020-04-21 13:23
Unstable mutagen doesn't penetrate skin.

Will close this as not a bug in some time unless I'm missing something in which case please do clarify.

**Closed** 2020-04-22 05:47 UTC
Labels: wontfix
