### ISSUE TITLE
Beepsky is super-AA.

### ISSUE THREAD

**Issue by HBS-System** [goonstation/goonstation#9543] opened 2022-07-09 03:36 UTC
### Labels

[MAJOR]

### Description

A beepsky can be used to open any door it has access to INCLUDING ARMORY.

### Steps to reproduce

1. Pull a Beepsky, preferably a non-roaming one.
2. Right click an airlock when the Beepsky is within a one tile radius of said airlock.
3. Click the pick up / left click interaction on the menu of the floor tile under the airlock to move the Beepsky to the airlock's tile. Bam! The airlock is now open.

### Expected Behavior

I expect this to not be a freely available source of all access for any player who grabs a beepsky.

### Additional Information & Screenshots

![hhjOuDQGkj](https://user-images.githubusercontent.com/34522718/178089851-6f2af697-e3f1-4f03-a253-608dc0740ddc.png)

**Comment by nefarious6th** [comment] 2022-07-09 06:24
Duplicate of #9057

**Closed** 2022-07-09 13:08 UTC
Labels: bug, bug - major
