### ISSUE TITLE
Worn back sprite of golden tranq gun sprite is whack

### ISSUE THREAD

**Issue by Mantweerp** [goonstation/goonstation#16638] opened 2023-10-25 09:00 UTC
### Labels

[BUG] [MINOR]

### Description

The sprite of the golden tranquilizer gun, when put on your back, appears to be a default backpack but with the missing texture overlay from half life

### Steps to reproduce

1. Claim the golden gun reward you get from the helios medal while holding the tranquilizer gun
2. Put the tranquilizer gun on your back
3. its purple and black

### Expected Behavior

For the tranquilizer gun on my back to be cool and gold and not stupid and purple and black

**Comment by AXLFAN2000** [comment] 2023-12-25 18:38
Duplicate of #16551

**Closed by AXLFAN2000** 2023-12-25 18:38 UTC
Labels: C-Bug, P-Minor
