### ISSUE TITLE
capsule machine doesn't update visually when righted

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#12649] opened 2023-01-06 20:42 UTC
### Labels

[BUG][minor]

### Description

Title

### Steps to reproduce

1. Find a capsule machine on its side
2. Right it
3. See error

### Expected Behavior

correct sprite

**Comment by TealSeer** [comment] 2023-10-22 00:26
Duplicate of #9757

**Closed by TealSeer** 2023-10-22 00:26 UTC
Labels: C-Bug, P-Minor, E-Verified
