### ISSUE TITLE
borgers turn player monkeys into cleanbots

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#3112] opened 2020-12-20 02:24 UTC
[BUG]

**Describe the bug**
Somewhere along the line borgers started turning NPC monkeys into cleanbots instead of braindead cyborgs.  However, this applies to player monkeys too.

**To Reproduce**
1. Be a player monkey.
2. Touch a borger.
3. Explode into bucket.
4. Presumably fail to control bucket but I haven't tested that myself.

**Expected behavior**
Player monkeys become player cyborgs, remaining in the round.

**Comment by ryebek** [comment] 2020-12-20 05:22
This is intentional, and one of the things I didn't change when doing my NPC/player monkey code check stuff, due to the general consensus on the discord being "this should still happen". Feel free to make a post on the forums if you feel it should be changed, but this is intended behaviour, so I'm going to close this issue.

**Closed by ryebek** 2020-12-20 05:22 UTC
Labels: bug
